# Generated by Django 5.1.6 on 2025-03-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('jira_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('jira_base_url', models.URLField(blank=True, null=True)),
                ('jira_api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('board_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sprint_name', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
